---
- name: Deploying Java Application
  become: true
  hosts: dev_app
  gather_facts: true

  tasks:
  - name: Installing Git In Amazon Linux OS
    yum: 
     name: git
     state: present
    when: ansible_facts ['distribution'] in ['Amazon']


  - name: Installing Git in Ubuntu OS
    apt: 
     name: git
     state: present
    when: ansible_facts ['distribution'] in ['Ubuntu']


  - name: Cloning Git Repo
    git:
     repo: https://github.com/techbleat/stockprice.git
     dest: /home/ec2-user/stockprice
    when: ansible_facts ['distribution'] in ['Amazon']

  - name: Cloning Git Repo
    git:
     repo: https://github.com/techbleat/stockprice.git
     dest: /home/ubuntu/stockprice
    when: ansible_facts ['distribution'] in ['Ubuntu']
  
  - name: Installing Java on Amazon Linux OS
    yum:
     name: java-17-amazon-corretto
     state:  present
    when: ansible_facts ['distribution'] in ['Amazon']

  - name: Update apt package list
    apt:
      update_cache: yes
    when: ansible_facts ['distribution'] in ['Ubuntu']

  - name: Installing Java on Ubuntu OS
    apt:
     name: openjdk-17-jdk
     state: present
    when: ansible_facts ['distribution'] in ['Ubuntu']

  - name: Installing Maven on Amazon Linux OS
    yum:
     name: maven
     state: present
    when: ansible_facts ['distribution'] in ['Amazon']

  - name: Installing Maven on Ubuntu OS
    apt:
     name: maven
     state: present
    when: ansible_facts ['distribution'] in ['Ubuntu']

  - name: Building Java Application
    shell: mvn clean install 
    args:
     chdir: /home/ec2-user/stockprice
    register: build_output
    when: ansible_facts ['distribution'] in ['Amazon']

  - name: Building Java Application
    shell: mvn clean install 
    args:
     chdir: /home/ubuntu/stockprice
    register: build_output
    when: ansible_facts ['distribution'] in ['Ubuntu']
    

  - name: Show Build Logs
    debug: 
      var: build_output.stdout_lines 

  - name: Creating Service file
    file:
     path: /etc/systemd/system/stockprice.service
     state: touch
  
  - name: Configuring stockprice.service file
    template:
     src: templates/stockprice.service.j2
     dest: /etc/systemd/system/stockprice.service
    vars:
     node_user: "ec2-user"
    when: ansible_facts ['distribution'] in ['Amazon']

  - name: Configuring stockprice.service file
    template:
     src: templates/stockprice.service.j2
     dest: /etc/systemd/system/stockprice.service
    vars:
     node_user: "ubuntu"
    when: ansible_facts ['distribution'] in ['Ubuntu']

  - name: Reloading stockprice.service 
    systemd:
     daemon_reload: yes

  - name: Starting the stockprice.service 
    systemd:
     name: stockprice.service
     state: started