- name: Installing Prometheus and Grafana in a container
  become: true 
  hosts: dev_monitor
  gather_facts: true 

  tasks:
   - name: Creating prometheus.yml file
     file:
      path: /home/ec2-user/prometheus.yml
      state: touch
   - name: Configuring prometheus.yml
     template:
      src: templates/prometheus.yml.j2
      dest: /home/ec2-user/prometheus.yml

   - name: Install  docker
     yum:
      name: docker
      state: present

   - name: Install  docker
     service:
      name: docker
      state: started
   

   - name: Install Docker-Compose
     shell: |
      curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) \
      -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose

   - name: Install Git
     yum: 
      name: git
      state: present

   - name: Git clone docker-compose file
     git: 
      repo: 'https://github.com/uthmanakz/docker-folder.git'
      dest: /home/ec2-user/docker-folder/
    
   - name: Running Prometheus as docker container
     shell: |
      cd docker-folder
      docker-compose up -d prometheus
