---
- name: Installing nginx on web nodes
  become: true
  hosts: dev_web
  gather_facts:

  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present
      when: ansible_facts ['distribution'] in ['Amazon']

    - name: Install Docker 
      apt:
       name: docker.io
       state: present
      when: ansible_facts ['distribution'] in ['Ubuntu']

    - name: Start Docker
      service:
        name: docker
        state: started

    - name: Install Docker-Compose
      shell: |
        curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) \
        -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Installing Git
      yum:
        name: git
        state: present
      when: ansible_facts ['distribution'] in ['Amazon']

    - name: Installing Git
      apt:
        name: git
        state: present
      when: ansible_facts ['distribution'] in ['Ubuntu']


    - name: Cloning docker-compose.yml file
      git:
        repo: 'https://github.com/uthmanakz/docker-folder.git'
        dest: /home/ec2-user/docker-folder/
      when: ansible_facts ['distribution'] in ['Amazon']

    - name: Configuring docker-compose.yml file
      template:
       src: templates/docker-compose.yml.j2
       dest: /home/ec2-user/docker-folder/docker-compose.yml
      when: ansible_facts ['distribution'] in ['Amazon']


    - name: Cloning docker-compose.yml file
      git:
        repo: 'https://github.com/uthmanakz/docker-folder.git'
        dest: /home/ubuntu/docker-folder/
      when: ansible_facts ['distribution'] in ['Ubuntu']

    - name: Configuring docker-compose.yml file
      template:
       src: templates/docker-compose.yml.j2
       dest: /home/ubuntu/docker-folder/docker-compose.yml
      when: ansible_facts ['distribution'] in ['Ubuntu']



    - name: Running docker-compose file
      shell: |
        cd docker-folder
        docker-compose up -d nginx-prometheus-exporter