---
- name: Installing Nginx
  become: true
  hosts: dev_web
  gather_facts: true

  tasks:
    - name: Install Nginx
      yum:
       name: nginx
       state: present
      when: ansible_facts ['distribution'] in ['Amazon']

    - name: Install Nginx Ubuntu
      apt:
        name: nginx
        state: present
      when: ansible_facts ['distribution'] in ['Ubuntu']

    - name: Start Nginx
      service:
        name: nginx
        state: started