---
- name: Installing Nginx
  become: true
  hosts: dev_web
  gather_facts: true

  tasks:
    - name: Install Nginx
      yum:
       name: nginx
       state: present
      when: ansible_facts ['distribution'] in ['Amazon']

    - name: Install Nginx Ubuntu
      apt:
        name: nginx
        state: present
      when: ansible_facts ['distribution'] in ['Ubuntu']

    - name: Start Nginx
      service:
        name: nginx
        state: started

    - name: Adding hosts in nginx.conf file
      template:
       src: templates/nginx.conf.j2
       dest: /etc/nginx/nginx.conf
      vars:
       nginx_user: 'nginx'
      when: ansible_facts ['distribution'] in ['Amazon']

    - name: Adding host in nginx.conf file
      template:
       src: templates/nginx.conf.j2
       dest: /etc/nginx/nginx.conf
      vars: 
       nginx_user: 'www-data'
      when: ansible_facts ['distribution'] in ['Ubuntu'] 

    - name: Reloading nginx.conf file 
      service:
       name: nginx
       state: reloaded